### PR TITLE
GSLUX-457: Deploy to gh pages

### PR DESCRIPTION
**Pull request by AlitaBernachot**
### JIRA issue

https://jira.camptocamp.com/browse/GSLUX-457

### Description

Add new workflow to deploy on github pages.

### CODE REVIEW

**Comment by AlitaBernachot** [comment]
App is available at: https://geoportail-luxembourg.github.io/luxembourg-geoportail/GSLUX-457/

**Comment by AlitaBernachot** [comment]
paths to i18n assets are broken https://geoportail-luxembourg.github.io/assets/locales/tooltips.fr.json

**Review by fgravin — COMMENTED** [review]
Very good, working great :+1: 
Please squash your commit history, I guess one commit is enough
Also you missed to add the cleanup pipeline. The folder which are pushed in the gh-pages branches are not removed !
Thanks

**Comment by AlitaBernachot** [comment]
Added cleanup pipeline and squashed history.

**Review by fgravin — APPROVED** [review]

**Pull request merged**
